name: ppanda
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_colorpicker: ^0.2.6
  google_fonts: ^0.3.9


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
  - assets/images/ppanda.png
  - assets/images/item1.jpg
  - assets/images/item2.jpg
  - assets/images/item3.jpg
  - assets/images/item4.jpg
  - assets/images/item5.jpg
  - assets/images/item6.jpg
  - assets/images/item7.jpg
  - assets/images/item9.jpg
  - assets/images/item10.jpg
  - assets/images/item11.jpg
  - assets/images/item12.jpg
  - assets/images/item13.jpg
  - assets/images/item14.jpg
  - assets/images/item15.jpg
  - assets/images/item16.jpg
  - assets/images/item17.jpg
  - assets/images/item18.jpg
  - assets/images/item19.jpg
  - assets/images/item20.jpg
  - assets/images/item21.jpg
  - assets/images/item22.jpg
  - assets/images/item23.jpg
  - assets/images/item24.jpg
  - assets/images/item25.jpg
  - assets/images/item26.jpg
  - assets/images/item27.jpg
  - assets/images/item28.jpg
  - assets/images/item29.jpg
  - assets/images/item30.jpg
  - assets/images/item31.jpg
  - assets/images/item32.jpg
  - assets/images/item33.jpg
  - assets/images/item34.jpg
  - assets/images/item35.jpg
  - assets/images/item36.jpg
  - assets/images/item37.jpg
  - assets/images/item38.jpg
  - assets/images/item39.jpg
  - assets/images/item40.jpg
  - assets/images/item41.jpg
  - assets/images/item42.jpg
  - assets/images/item43.jpg
  - assets/images/item44.jpg
  - assets/images/item45.jpg
  - assets/images/item46.jpg
  - assets/images/item47.jpg
  - assets/images/item48.jpg
  - assets/images/item49.jpg
  - assets/images/item50.jpg
  - assets/images/item51.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
